version: 2.1
jobs:
  build:
    docker:
      - image: harumaxy/hugoci
    steps:
      - checkout
      - run:
          name: "Update Academy"
          command: git submodule update --init --recursive 
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo
      # - run:
      #     name: "Test Website"
      #     command: htmlproofer public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      # - run:
      #     name:  get firebase-tools
      #     command: apt update -y && apt install -y npm && npm install -g firebase-tools
      - deploy:
          name: Deploy Website to Firebase Hosting
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project $FIREBASE_PROJECT_ID
