version: 2
jobs:
  build: # ジョブ名
    branches:
      only:
        - "master"
    docker:
      - image: circleci/node:10.7 # ジョブ実行環境のDockerイメージを記述
    steps:
      - checkout # ソースコードのチェックアウト
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: npm install
          command: npm i -g firebase tools
      - run:
          name: get hugo
          command: apt update -y && apt install -y hugo
      - run:
          name: build
          command: hugo
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN # プロジェクト上のfirebase-toolsでデプロイします
